import { lstat, mkdir, readFile, realpath, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PraxaAuthMode, PraxaInitTarget } from "./arguments.js";

const generatedMarker = "Generated by @praxa/cli. Do not put credentials in this file.";
const configSchemaVersion = "praxa-project-config-v1";

type JsonRecord = Record<string, unknown>;
type PlannedFile = Readonly<{
  relativePath: string;
  content: string;
  action: "create" | "update" | "unchanged";
}>;

export type PraxaInitOptions = Readonly<{
  baseUrl: string;
  projectDirectory: string;
  targets: readonly PraxaInitTarget[];
  authMode: PraxaAuthMode;
  dryRun: boolean;
  force: boolean;
}>;

export type PraxaInitResult = Readonly<{
  schemaVersion: "praxa-init-result-v1";
  projectDirectory: string;
  baseUrl: string;
  mcpUrl: string;
  authMode: PraxaAuthMode;
  dryRun: boolean;
  files: readonly Readonly<{ path: string; action: PlannedFile["action"] }>[];
  nextSteps: readonly string[];
}>;

function object(value: unknown): JsonRecord | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as JsonRecord
    : undefined;
}

function prettyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

async function optionalFile(filePath: string): Promise<string | undefined> {
  try {
    const stat = await lstat(filePath);
    if (stat.isSymbolicLink() || !stat.isFile()) {
      throw new Error(`Refusing to replace non-regular file: ${filePath}`);
    }
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (object(error)?.["code"] === "ENOENT") return undefined;
    throw error;
  }
}

async function assertSafeProjectParents(root: string, relativePath: string): Promise<void> {
  let current = root;
  for (const segment of relativePath.split("/").slice(0, -1)) {
    current = path.join(current, segment);
    const stat = await lstat(current).catch((error: unknown) => {
      if (object(error)?.["code"] === "ENOENT") return undefined;
      throw error;
    });
    if (stat === undefined) return;
    if (stat.isSymbolicLink() || !stat.isDirectory()) {
      throw new Error(`Refusing unsafe project directory: ${current}`);
    }
  }
}

async function optionalProjectFile(root: string, relativePath: string): Promise<string | undefined> {
  await assertSafeProjectParents(root, relativePath);
  return optionalFile(path.join(root, relativePath));
}

function actionFor(existing: string | undefined, content: string): PlannedFile["action"] {
  if (existing === undefined) return "create";
  return existing === content ? "unchanged" : "update";
}

function jsonServerConfig(baseUrl: string, authMode: PraxaAuthMode, client: "claude" | "cursor"): JsonRecord {
  const headers = authMode === "oauth"
    ? {}
    : {
        Authorization: client === "claude"
          ? "Bearer ${PRAXA_ACCESS_TOKEN}"
          : "Bearer ${env:PRAXA_ACCESS_TOKEN}",
      };
  return {
    type: "http",
    url: `${baseUrl}/mcp`,
    ...(Object.keys(headers).length === 0 ? {} : { headers }),
  };
}

function mergeJsonServer(
  source: string | undefined,
  topLevelKey: "mcpServers" | "servers",
  server: JsonRecord,
  force: boolean,
  fileLabel: string,
): JsonRecord {
  let root: JsonRecord = {};
  if (source !== undefined) {
    try {
      const parsed = object(JSON.parse(source));
      if (parsed === undefined) throw new Error("root_not_object");
      root = parsed;
    } catch {
      throw new Error(`${fileLabel} is not a JSON object; no files were changed`);
    }
  }
  const servers = object(root[topLevelKey]) ?? {};
  if (root[topLevelKey] !== undefined && object(root[topLevelKey]) === undefined) {
    throw new Error(`${fileLabel} has a non-object ${topLevelKey}; no files were changed`);
  }
  const existing = servers["praxa"];
  if (existing !== undefined && JSON.stringify(existing) !== JSON.stringify(server) && !force) {
    throw new Error(`${fileLabel} already configures praxa; rerun with --force to replace only that entry`);
  }
  return { ...root, [topLevelKey]: { ...servers, praxa: server } };
}

function mergeVscode(
  source: string | undefined,
  baseUrl: string,
  authMode: PraxaAuthMode,
  force: boolean,
): JsonRecord {
  const server = authMode === "oauth"
    ? { type: "http", url: `${baseUrl}/mcp` }
    : {
        type: "http",
        url: `${baseUrl}/mcp`,
        headers: { Authorization: "Bearer ${input:praxa-access-token}" },
      };
  const root = mergeJsonServer(source, "servers", server, force, ".vscode/mcp.json");
  if (authMode === "oauth") return root;
  const inputs = root["inputs"];
  if (inputs !== undefined && !Array.isArray(inputs)) {
    throw new Error(".vscode/mcp.json has non-array inputs; no files were changed");
  }
  const requested = {
    type: "promptString",
    id: "praxa-access-token",
    description: "Short-lived delegated Praxa OAuth access token",
    password: true,
  };
  const entries = [...(inputs ?? [])] as unknown[];
  const index = entries.findIndex((entry) => object(entry)?.["id"] === requested.id);
  if (index >= 0 && JSON.stringify(entries[index]) !== JSON.stringify(requested) && !force) {
    throw new Error(".vscode/mcp.json already defines praxa-access-token; rerun with --force to replace only that input");
  }
  if (index >= 0) entries[index] = requested;
  else entries.push(requested);
  return { ...root, inputs: entries };
}

function codexSection(baseUrl: string, authMode: PraxaAuthMode): string {
  return [
    "[mcp_servers.praxa]",
    `url = ${JSON.stringify(`${baseUrl}/mcp`)}`,
    ...(authMode === "environment" ? ['bearer_token_env_var = "PRAXA_ACCESS_TOKEN"'] : []),
    "enabled = true",
  ].join("\n");
}

function mergeCodex(source: string | undefined, section: string, force: boolean): string {
  if (source === undefined || source.trim().length === 0) return `${section}\n`;
  const lines = source.replaceAll("\r\n", "\n").replaceAll("\r", "\n").split("\n");
  const headerPattern = /^\s*\[([^\x5D]+)\]\s*(?:#.*)?$/u;
  const start = lines.findIndex((line) => headerPattern.exec(line)?.[1] === "mcp_servers.praxa");
  if (start < 0) return `${source.endsWith("\n") ? source : `${source}\n`}\n${section}\n`;
  let end = lines.length;
  for (let index = start + 1; index < lines.length; index += 1) {
    const table = headerPattern.exec(lines[index] ?? "")?.[1];
    if (table !== undefined && table !== "mcp_servers.praxa" && !table.startsWith("mcp_servers.praxa.")) {
      end = index;
      break;
    }
  }
  const current = lines.slice(start, end).join("\n").trim();
  if (current === section) return source.endsWith("\n") ? source : `${source}\n`;
  if (!force) {
    throw new Error(".codex/config.toml already configures mcp_servers.praxa; rerun with --force to replace only that table");
  }
  const replaced = [...lines.slice(0, start), ...section.split("\n"), ...lines.slice(end)].join("\n");
  return replaced.endsWith("\n") ? replaced : `${replaced}\n`;
}

function guide(baseUrl: string, targets: readonly PraxaInitTarget[], authMode: PraxaAuthMode): string {
  const authentication = authMode === "oauth"
    ? "Open your client's MCP controls and authenticate Praxa in the browser. OAuth tokens stay in the client's credential store."
    : "Inject `PRAXA_ACCESS_TOKEN` with your password manager, CI secret store, or shell for the client process. Never commit the token or a provider credential.";
  return `<!-- ${generatedMarker} -->
# Praxa agent setup

Praxa is configured for \`${baseUrl}\` in: ${targets.map((target) => `\`${target}\``).join(", ")}.

1. ${authentication}
2. Restart the selected agent client and enable or trust the project-scoped \`praxa\` MCP server.
3. Run \`npx @praxa/cli doctor\` to verify the delegated, read-only gateway path.
4. Ask the agent to list Praxa tools before creating a mission. Mutations require explicit idempotency keys and remain subject to server policy.

The generated files contain endpoint metadata only. Models propose; deterministic policy authorizes; the broker executes; independent evidence verifies external effects.
`;
}

function projectConfig(baseUrl: string, targets: readonly PraxaInitTarget[], authMode: PraxaAuthMode): string {
  return prettyJson({
    schemaVersion: configSchemaVersion,
    baseUrl,
    mcpUrl: `${baseUrl}/mcp`,
    authMode,
    targets,
  });
}

async function planFiles(root: string, options: PraxaInitOptions): Promise<PlannedFile[]> {
  const files: Array<Readonly<{ relativePath: string; content: string; managed?: boolean }>> = [
    { relativePath: ".praxa/config.json", content: projectConfig(options.baseUrl, options.targets, options.authMode), managed: true },
    { relativePath: ".praxa/SETUP.md", content: guide(options.baseUrl, options.targets, options.authMode), managed: true },
  ];
  for (const target of options.targets) {
    if (target === "codex") {
      const relativePath = ".codex/config.toml";
      const existing = await optionalProjectFile(root, relativePath);
      files.push({ relativePath, content: mergeCodex(existing, codexSection(options.baseUrl, options.authMode), options.force) });
    } else if (target === "claude" || target === "cursor") {
      const relativePath = target === "claude" ? ".mcp.json" : ".cursor/mcp.json";
      const existing = await optionalProjectFile(root, relativePath);
      files.push({
        relativePath,
        content: prettyJson(mergeJsonServer(existing, "mcpServers", jsonServerConfig(options.baseUrl, options.authMode, target), options.force, relativePath)),
      });
    } else if (target === "vscode") {
      const relativePath = ".vscode/mcp.json";
      const existing = await optionalProjectFile(root, relativePath);
      files.push({ relativePath, content: prettyJson(mergeVscode(existing, options.baseUrl, options.authMode, options.force)) });
    } else {
      files.push({
        relativePath: ".env.praxa.example",
        content: `# ${generatedMarker}\nPRAXA_BASE_URL=${options.baseUrl}\nPRAXA_ACCESS_TOKEN=\n`,
        managed: true,
      });
      const relativePath = ".gitignore";
      const existing = await optionalProjectFile(root, relativePath);
      const line = ".env.praxa";
      const content = existing === undefined
        ? `${line}\n`
        : existing.split(/\r?\n/u).includes(line)
          ? existing
          : `${existing.endsWith("\n") ? existing : `${existing}\n`}${line}\n`;
      files.push({ relativePath, content });
    }
  }
  const planned: PlannedFile[] = [];
  for (const file of files) {
    const existing = await optionalProjectFile(root, file.relativePath);
    if (
      existing !== undefined
      && file.managed === true
      && !existing.includes(generatedMarker)
      && !existing.includes(configSchemaVersion)
      && existing !== file.content
      && !options.force
    ) {
      throw new Error(`${file.relativePath} is not Praxa-managed; rerun with --force to replace it`);
    }
    planned.push({ ...file, action: actionFor(existing, file.content) });
  }
  return planned;
}

async function atomicWrite(root: string, relativePath: string, content: string): Promise<void> {
  await assertSafeProjectParents(root, relativePath);
  const filePath = path.join(root, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await assertSafeProjectParents(root, relativePath);
  const temporary = `${filePath}.praxa-${process.pid}-${Date.now()}.tmp`;
  try {
    await writeFile(temporary, content, { encoding: "utf8", mode: 0o600, flag: "wx" });
    await rename(temporary, filePath);
  } catch (error) {
    await unlink(temporary).catch(() => undefined);
    throw error;
  }
}

export async function initializePraxaProject(options: PraxaInitOptions): Promise<PraxaInitResult> {
  const requestedRoot = path.resolve(options.projectDirectory);
  const root = await realpath(requestedRoot);
  const stat = await lstat(root);
  if (!stat.isDirectory()) throw new Error("--project-dir must name an existing directory");
  const files = await planFiles(root, options);
  if (!options.dryRun) {
    for (const file of files) {
      if (file.action !== "unchanged") await atomicWrite(root, file.relativePath, file.content);
    }
  }
  return {
    schemaVersion: "praxa-init-result-v1",
    projectDirectory: root,
    baseUrl: options.baseUrl,
    mcpUrl: `${options.baseUrl}/mcp`,
    authMode: options.authMode,
    dryRun: options.dryRun,
    files: files.map((file) => ({ path: file.relativePath, action: file.action })),
    nextSteps: options.authMode === "oauth"
      ? ["Authenticate Praxa from the selected MCP client", "Restart the client", "Run: npx @praxa/cli doctor"]
      : ["Inject PRAXA_ACCESS_TOKEN without committing it", "Restart the selected client", "Run: npx @praxa/cli doctor"],
  };
}

export async function loadPraxaProjectBaseUrl(projectDirectory: string): Promise<string | undefined> {
  const requestedRoot = path.resolve(projectDirectory);
  const root = await realpath(requestedRoot);
  const source = await optionalProjectFile(root, ".praxa/config.json");
  if (source === undefined) return undefined;
  try {
    const config = object(JSON.parse(source));
    const baseUrl = config?.["baseUrl"];
    return config?.["schemaVersion"] === configSchemaVersion && typeof baseUrl === "string"
      ? baseUrl
      : undefined;
  } catch {
    return undefined;
  }
}
